src/oe_project/oe_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dj_data.urls')),
    path('', include('write.urls')),
    path('', include('accounts.urls')),
]

src/oe_project/write/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('planning', views.planning, name='planning'),
    path('history', views.history, name='history'),
    path('chart', views.chart, name='chart'),
    path('check-plan', views.check_plan, name='check_plan'),
    path('test-input/plan-<str:pk_plan>', views.test_input, name='test_input'),
]

src/oe_project/write/models.py
from django.db import models
from django.utils.timezone import now
from dj_data.models import *
# Create your models here.


class WriteData(models.Model):
    start = models.BooleanField(default=False)
    qty_actual = models.PositiveIntegerField()
    timestamps = models.FloatField()
    machine = models.BooleanField(default=True)
    material = models.BooleanField(default=True)
    quality = models.BooleanField(default=True)
    other = models.BooleanField(default=True)
    date = models.CharField(max_length=10)
    department = models.ForeignKey(
        Department, on_delete=models.CASCADE, null=True)
    line = models.ForeignKey(Line, on_delete=models.CASCADE, null=True)
    process = models.ForeignKey(DJProcess, on_delete=models.CASCADE, null=True)
    version = models.PositiveIntegerField()
    shift_work = models.BooleanField(default=False)
    qty_plan = models.PositiveIntegerField()


class Planning(models.Model):
    timestamp = models.FloatField()
    date = models.CharField(max_length=10)
    time = models.CharField(max_length=10)
    department = models.CharField(max_length=3)
    line = models.CharField(max_length=1)
    model = models.CharField(max_length=100)
    version = models.PositiveIntegerField()
    shift_work = models.BooleanField()
    qty_plan = models.PositiveIntegerField()


class LatestData(models.Model):
    start = models.BooleanField(default=False)
    qty_actual = models.PositiveIntegerField()
    timestamps = models.FloatField(unique=True)
    machine = models.BooleanField(default=True)
    material = models.BooleanField(default=True)
    quality = models.BooleanField(default=True)
    other = models.BooleanField(default=True)
    date = models.CharField(max_length=10)
    department = models.ForeignKey(
        Department, on_delete=models.CASCADE, null=True)
    line = models.ForeignKey(Line, on_delete=models.CASCADE, null=True)
    process = models.ForeignKey(DJProcess, on_delete=models.CASCADE, null=True)
    version = models.PositiveIntegerField()
    shift_work = models.BooleanField(default=False)
    qty_plan = models.PositiveIntegerField()

src/oe_project/write/forms.py
from django import forms
from django.forms import ModelForm
from .models import models, DJModel, Department, Line, DJGroupModel
import datetime

class DateInput(forms.DateInput):
    input_type = 'date'

class DepartmentForm(ModelForm):
    class Meta:
        model = Department
        fields = '__all__'
    
class LineForm(ModelForm):
    class Meta:
        model = Line
        fields = '__all__'

class DJGroupModelForm(ModelForm):
    class Meta:
        model = DJGroupModel
        fields = '__all__'

src/oe_project/write/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.utils import timezone
from django.conf import settings
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta
import json

from .models import *
from dj_data.models import *


# Create your views here.
brand = 'DONGJIN VIETNAM J.S.C'


def calc_delta(delta_second, shift_3rd, begin_time, end_time):
    begin_time = datetime.fromtimestamp(begin_time)
    end_time = datetime.fromtimestamp(end_time)
    if shift_3rd == 1:
        shift_1 = datetime(
            end_time.year, end_time.month, end_time.day, 10, 00, 0)
        shift_2 = datetime(
            end_time.year, end_time.month, end_time.day, 18, 00, 0)
        tomorrow = end_time + timedelta(days=1)
        shift_3 = datetime(
            tomorrow.year, tomorrow.month, tomorrow.day, 2, 00, 0
        )

        if begin_time < shift_1:
            if end_time > shift_1:
                delta_second = delta_second - 1800
        if begin_time < shift_2:
            if end_time > shift_2:
                delta_second = delta_second - 1800
        if begin_time < shift_3:
            if end_time > shift_3:
                delta_second = delta_second - 2700

    else:
        shift_1 = datetime(
            end_time.year, end_time.month, end_time.day, 10, 00, 0)
        shift_2 = datetime(
            end_time.year, end_time.month, end_time.day, 14, 00, 0)
        shift_3 = datetime(
            end_time.year, end_time.month, end_time.day, 22, 00, 0)
        tomorrow = end_time + timedelta(days=1)
        shift_4 = datetime(
            tomorrow.year, tomorrow.month, tomorrow.day, 2, 00, 0
        )

        if begin_time < shift_1:
            if end_time > shift_1:
                delta_second = delta_second - 1800
        if begin_time < shift_2:
            if end_time > shift_2:
                delta_second = delta_second - 1800
        if begin_time < shift_3:
            if end_time > shift_3:
                delta_second = delta_second - 1800
        if begin_time < shift_4:
            if end_time > shift_4:
                delta_second = delta_second - 2700

    return delta_second


def get_arr_group_model(today_plan):
    arr = []
    if today_plan:
        # Get today processes in model
        selected_group = DJProcess.objects.filter(model__description=today_plan.model,
                                                department__name=today_plan.department)
        day = datetime.fromtimestamp(today_plan.timestamp).strftime(
            '%Y-%m-%d')
        for process in selected_group:  # Loop through all models in group
            write_obj = WriteData.objects.filter(date=day, department__name=today_plan.department,
                                                 line__name=today_plan.line, process=process)
            if write_obj:
                last_line = write_obj.last()
                first_line = (WriteData.objects.filter(date=last_line.date, department__name=last_line.department,
                                                       line__name=last_line.line, process__name=last_line.process.name,
                                                       version=last_line.version, qty_plan=last_line.qty_plan)).first()
                previous_line = last_line
                if len(write_obj) > 1:  # If found > 1 element in write object
                    # Reverse object, get previous line of last line
                    previous_line = write_obj.order_by('-id')[1]

                if last_line.qty_actual != 0:
                    # Calculator fields
                    start_time = datetime.fromtimestamp(
                        first_line.timestamps).strftime('%H:%M:%S')
                    end_time = datetime.fromtimestamp(
                        last_line.timestamps).strftime('%H:%M:%S')

                    per_finish = last_line.qty_actual / last_line.qty_plan * 100
                    delta_second = last_line.timestamps - first_line.timestamps

                    if last_line.qty_actual == previous_line.qty_actual:  # If qty_actual not change
                        before_actual = (WriteData.objects.filter(qty_actual=last_line.qty_actual, date=last_line.date,
                                                                  department__name=last_line.department, line__name=last_line.line,
                                                                  process__name=last_line.process.name, version=last_line.version,
                                                                  qty_plan=last_line.qty_plan)).first()
                        # End time and delta second just change when qty_actual change
                        end_time = datetime.fromtimestamp(
                            before_actual.timestamps).strftime('%H:%M:%S')
                        delta_second = before_actual.timestamps - first_line.timestamps

                    # Calculate time of shift work
                    delta_second = calc_delta(delta_second, last_line.shift_work,
                                              first_line.timestamps, last_line.timestamps)

                    st_actual = (delta_second + process.st) / \
                        last_line.qty_actual
                    data = {
                        'start': last_line.start,
                        'qty_actual': last_line.qty_actual,
                        'timestamps': last_line.timestamps,
                        'machine': last_line.machine,
                        'material': last_line.material,
                        'quality': last_line.quality,
                        'other': last_line.other,
                        'date': last_line.date,
                        'version': last_line.version,
                        'shift_work': last_line.shift_work,
                        'department': last_line.department.name,
                        'line': last_line.line.name,
                        'model_name': process.model.description,
                        'process_name': process.description,
                        'st_plan': f"{process.st:.2f}",
                        'qty_plan': last_line.qty_plan,

                        'start_time': start_time,
                        'end_time': end_time,
                        'st_actual': f"{st_actual:.2f}",
                        'per_finish': f"{per_finish:.2f}",
                    }
                else:
                    data = {
                        'start': False,
                        'qty_actual': 0,
                        'timestamps': last_line.timestamps,
                        'machine': True,
                        'material': True,
                        'quality': True,
                        'other': True,
                        'date': last_line.date,
                        'version': last_line.version,
                        'shift_work': last_line.shift_work,
                        'department': last_line.department.name,
                        'line': last_line.line.name,
                        'model_name': process.model.description,
                        'process_name': process.description,
                        'st_plan': '0.00',
                        'qty_plan': 0,

                        'start_time': '00:00:00',
                        'end_time': '00:00:00',
                        'st_actual': '0.00',
                        'per_finish': '0.00',
                    }
                arr.append(data)

    return arr


def get_arr_plan(today_plan):
    arr = []
    if today_plan:
        # Get today processes in model
        selected_group = DJProcess.objects.filter(model__description=today_plan.model,
                                                department__name=today_plan.department)

        for i in range(0, len(selected_group)):
            data = {
                'Start': 0,
                'Q\'ty Actual': 0,
                'Timestamp': today_plan.timestamp,
                'Machine': 1,
                'Material': 1,
                'Quality': 1,
                'Other': 1,
                'Date': today_plan.date,
                'Time': today_plan.time,
                'Department Name': today_plan.department,
                'Department': selected_group[i].department.id,
                'Line Name': today_plan.line,
                'Line': Line.objects.get(name=today_plan.line).id,
                'Process Name': selected_group[i].description,
                'Process ID': selected_group[i].id,
                'Count Model In Group': len(selected_group),
                'Model Name': selected_group[i].model.description,
                'Model ID': selected_group[i].model.id,
                'Version': today_plan.version,
                'Shift Work': 1 if today_plan.shift_work else 0,
                'Q\'ty Plan': today_plan.qty_plan,
                'Finish %': 0,
                'ST Plan': 0,
                'ST Actual': 0,
            }
            arr.append(data)
    return arr


def get_arr_history(selected_plan):
    arr = []
    if selected_plan:
        # Get all plan of selected date
        for plan in selected_plan:
            # Get all model in group model of this plan
            selected_group = DJProcess.objects.filter(model__description=plan.model,
                                                    department__name=plan.department)

            day = datetime.fromtimestamp(plan.timestamp).strftime(
                '%Y-%m-%d')
            # Calculate for all model in selected group
            for process in selected_group:
                write_obj = WriteData.objects.filter(date=day, department__name=plan.department,
                                                     line__name=plan.line, process=process,
                                                     qty_plan=plan.qty_plan, version=plan.version)

src/oe_project/write/templates/write/check-plan.html
{% extends 'main.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/general.css' %}">
{% endblock head %}
{% block body %}
<div style="display: flex;">
    <div class="col-md-12">
        <form id="form-plan" name="form-plan" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-8">
                    <fieldset>
                        <legend>Check Plan Form</legend>
                        <label for="id_department">Department: </label>
                        <select id="id_department" name="department" required>
                            <option value="" class="opt-empty"></option>
                            {% for department in departments %}
                            <option value="{{ department }}">
                                {{ department }}
                            </option>
                            {% endfor %}
                        </select>
                        <br />
                        <label for="id_line">Line: </label>
                        <select id="id_line" name="line" required>
                            <option value="" class="opt-empty"></option>
                            {% for line in lines %}
                            <option value="{{ line }}">
                                {{ line }}
                            </option>
                            {% endfor %}
                        </select>
                        <br />
                        <label for="id_dj_model">Model: </label>
                        <select id="id_dj_model" name="dj_model" required>
                            <option value="" class="opt-empty"></option>
                            {% for item in dj_models %}
                            <option value="{{ item.description }}">{{ item.description }}</option>
                            {% endfor %}
                        </select>
                        <br />
                        <label for="plan">Q'ty Plan: </label>
                        <input id="plan" name="plan" type="number" min="1" step="1" required />
                        <br />
                        <label for="version">Version of plan: </label>
                        <input id="version" name="version" type="number" min="1" step="1" required />
                        <br />
                        <label for="check-shift">3rd shift: </label>
                        <input id="check-shift" name="check-shift" type="checkbox" />
                        <br />
                    </fieldset>
                </div>

                <div id="div-button" class="col-md-4">
                    <button id="btn-check-plan" name="btn-check-plan" type="submit" disabled>
                        Check Plan
                    </button>
                    <div class="note">
                        <b>Note:</b>
                        <p>Please fill information to check plan</p>
                    </div>
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                            {% if 'safe' in message.tags %} {{ message|safe }}
                            {% else %} {{ message }} {% endif %}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock body %}
{% block script %}
<script>
    jQuery(function ($) {
        // Detect user fill input
        $('#version').on('input', function () {
            $version = $('#version').val();
            if ($version === '') {
                $('#div-button button').attr('disabled', true);
                $('.note').fadeIn(600);
            } else {
                $('#div-button button').removeAttr('disabled');
                $('.note').fadeOut(600);
            }
        });
    });
</script>
{% endblock script %}

src/oe_project/write/templates/write/planning.html
{% extends 'main.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/general.css' %}">
{% endblock head %}
{% block body %}
<div style="display: flex;">
    <div class="col-md-12">
        <form id="form-plan" name="form-plan" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-8">
                    <fieldset>
                        <legend>Information Requirement</legend>
                        <label for="id_department">Department: </label>
                        <select id="id_department" name="department" required>
                            <option value="" class="opt-empty"></option>
                            {% for department in departments %}
                            <option value="{{ department }}">
                                {{ department }}
                            </option>
                            {% endfor %}
                        </select>
                        <br />
                        <label for="id_line">Line: </label>
                        <select id="id_line" name="line" required>
                            <option value="" class="opt-empty"></option>
                            {% for line in lines %}
                            <option value="{{ line }}">
                                {{ line }}
                            </option>
                            {% endfor %}
                        </select>
                        <br />
                        <label for="id_dj_model">Model: </label>
                        <select id="id_dj_model" name="dj_model" required>
                            <option value="" class="opt-empty"></option>
                            {% for item in dj_models %}
                            <option value="{{ item.description }}">{{ item.description }}</option>
                            {% endfor %}
                        </select>
                        <br />
                        <label for="plan">Q'ty Plan: </label>
                        <input id="plan" name="plan" type="number" min="1" step="1" required />
                        <br />
                        <label for="version">Version of plan: </label>
                        <input id="version" name="version" type="number" min="1" step="1" required />
                        <br />
                        <label for="check-shift">3rd shift: </label>
                        <input id="check-shift" name="check-shift" type="checkbox" />
                        <br />
                    </fieldset>
                </div>

                <div id="div-button" class="col-md-4">
                    <button id="btn-plan" name="btn-plan" type="submit" disabled>
                        Create Plan
                    </button>
                    <div class="note">
                        <b>Note:</b>
                        <p>Please fill information to create plan</p>
                    </div>
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                            {% if 'safe' in message.tags %} {{ message|safe }}
                            {% else %} {{ message }} {% endif %}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock body %}
{% block script %}
<script>
    jQuery(function ($) {
        // Detect user fill input
        $('#version').on('input', function () {
            $version = $('#version').val();
            if ($version === '') {
                $('#div-button button').attr('disabled', true);
                $('.note').fadeIn(600);
            } else {
                $('#div-button button').removeAttr('disabled');
                $('.note').fadeOut(600);
            }
        });
    });
</script>
{% endblock script %}

src/oe_project/write/templates/write/test-input.html
{% extends 'main.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/general.css' %}">
{% endblock head %}
{% block body %}
<div>
    <b>Note:</b> If your plan is a <b>new plan</b>, you need add <b>qty actual</b> first.
</div>
<div class="row">
    <style>
        .table-model {
            border: 1px solid black;
            margin: 50px 25px 0px;
        }

        .table-align:nth-child(odd) {
            padding-left: 0px;
        }

        .table-align:nth-child(even) {
            padding-right: 0px;
        }
    </style>
    {% for process in my_processes %}
    <div class="col-md-6 table-align">
        <form method='post'>
            {% csrf_token %}
            <div class="table-model">
                <div class="row">
                    <div class="col-md-4">
                        Department - Line: <b>{{ my_plan.department }} - {{ my_plan.line }}</b>
                    </div>
                    <div class="col-md-8">
                        Model: <b>{{ process.model.description }}-{{ process.description }}</b>
                        <input id="btn-process-{{ process.id }}" type="hidden" class="btn-process-id" name="btn-process-id"
                            value="{{ process.id }}">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        Qty Plan: <b>{{ my_plan.qty_plan }}</b>
                    </div>
                    <div class="col-md-4">
                        ST Plan: <b>{{ process.st }}</b>
                    </div>
                    <div class="col-md-4">
                        Version: <b>{{ my_plan.version }}</b>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label for="txt-qty-actual">Input Qty actual: </label>
                        <input type="number" min="1" id="txt-qty-actual" name="txt-qty-actual">
                        <div class="col-md-3" style="display: inline-block;">
                            <button class="btn-qty-actual" name="btn-qty-actual">
                                Add Qty
                            </button>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <button class="btn-other" name="btn-other">
                            Other
                        </button>
                    </div>
                    <div class="col-md-2">
                        <button class="btn-quality" name="btn-quality">
                            Quality
                        </button>
                    </div>
                    <div class="col-md-2">
                        <button class="btn-material" name="btn-material">
                            Material
                        </button>
                    </div>
                    <div class="col-md-2">
                        <button class="btn-machine" name="btn-machine">
                            Machine
                        </button>
                    </div>
                    <div class="col-md-2">
                        <button class="btn-on-off" name="btn-on-off">
                            On/Off
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    {% endfor %}
</div>
{% endblock body %}