src/oe_project/accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('profiles/<str:username>', views.profiles, name='profiles'),
    path('settings/<str:username>', views.settings, name='account_settings'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/oe_project/oe_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dj_data.urls')),
    path('', include('write.urls')),
    path('', include('accounts.urls')),
]

src/oe_project/write/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('planning', views.planning, name='planning'),
    path('history', views.history, name='history'),
    path('chart', views.chart, name='chart'),
    path('check-plan', views.check_plan, name='check_plan'),
    path('test-input/plan-<str:pk_plan>', views.test_input, name='test_input'),
]

src/oe_project/accounts/models.py
from django.db import models
# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db.models.fields import NullBooleanField

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    ROLE = (
        ('Guest', 'Guest'),
        ('Planner', 'Planner'),
        ('Tester', 'Tester'),
    )
    roles = models.CharField(max_length=25, choices=ROLE, default='Guest')
    bio = models.TextField(max_length=500, blank=True)
    avatar = models.ImageField(null=True, blank=True, upload_to=f'avatar')

src/oe_project/accounts/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class UserBioForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ('bio',)


class UserAvatarForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ('avatar',)


class UserProfileForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email',)
        widgets = {
            'birth_date': CustomUser(),
            'date_joined': forms.TextInput(),
            'last_login': forms.TextInput(),
        }


class UserPasswordForm(ModelForm):
    current_password = forms.CharField(widget=forms.PasswordInput())
    new_password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = CustomUser
        fields = ('current_password', 'new_password', 'confirm_password', )

src/oe_project/accounts/views.py
from django.contrib.auth.backends import UserModel
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth import update_session_auth_hash

from .forms import UserBioForm, UserAvatarForm, UserProfileForm, UserPasswordForm

# Create your views here.
brand = 'DONGJIN VIETNAM J.S.C'


def login_failed(request):
    messages.add_message(request, messages.ERROR,
                         'Username or Password is incorrect')


def loginPage(request):
    if request.user.is_authenticated:
        return redirect(request.GET.get('next', 'home'))
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(request.GET.get('next', 'home'))
            else:  # Login with email as username
                user_mail = ''
                try:
                    user_mail = User.objects.get(email=username)
                    user = authenticate(
                        request, username=user_mail.username, password=password)
                    if user is not None:
                        login(request, user)
                        return redirect(request.GET.get('next', 'home'))
                    else:
                        login_failed(request)
                except:
                    login_failed(request)

    return render(request, 'login.html')


def logoutPage(request):
    logout(request)
    return redirect('home')


@login_required(login_url='login')
def profiles(request, username):
    title = 'Profiles'
    user = request.user
    bio_form = UserBioForm()
    avatar_form = UserAvatarForm()

    if request.method == 'POST':
        if 'btn-change-bio' in request.POST:
            form = UserBioForm(request.POST, instance=user)
            if form.is_valid():
                form.save()

        if 'btn-change-avatar' in request.POST:
            form = UserAvatarForm(request.POST, request.FILES, instance=user)
            print(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect('profiles', username=username)

    context = {
        'brand': brand,
        'title': title,
        'bio_form': bio_form,
        'avatar_form': avatar_form,
    }
    return render(request, 'profiles.html', context=context)


@login_required(login_url='login')
def settings(request, username):
    title = 'Settings & Privacy'
    user = request.user
    password_form = UserPasswordForm()
    profile_form = UserProfileForm()

    if request.method == 'POST':
        if 'save-password' in request.POST:
            form = UserPasswordForm(request.POST, instance=user)
            if form.is_valid():
                setting = form.save(commit=False)
                current_password = form.cleaned_data['current_password']
                # Check user current password
                if check_password(current_password, user.password):
                    new_password = form.cleaned_data['new_password']
                    confirm_password = form.cleaned_data['confirm_password']
                    if new_password == confirm_password:
                        # Hash password
                        setting.password = make_password(new_password)
                        setting.save()
                        # Keep session when user change password
                        update_session_auth_hash(request, user)
                        messages.add_message(
                            request, messages.SUCCESS, 'Password update successfully.')

                    else:
                        messages.add_message(
                            request, messages.ERROR, "Password confirmation doesn't match password.")
                else:
                    messages.add_message(
                        request, messages.ERROR, 'Invalid password.')

        if 'save-profile' in request.POST:
            form = UserProfileForm(request.POST, instance=user)

            if form.is_valid():
                form.save()
                messages.add_message(
                    request, messages.SUCCESS, 'Profile updated.')
            else:
                messages.add_message(
                    request, messages.ERROR, 'Form is invalid.')

    context = {
        'brand': brand,
        'title': title,
        'password_form': password_form,
        'profile_form': profile_form,
    }
    return render(request, 'settings.html', context=context)

src/oe_project/accounts/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login</title>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="DONGJIN VIETNAM">
    <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'fontawesome-5.15.2/css/all.css' %}">
</head>

<body>
    <div id="right-sidebar" class="right-sidebar-notifcations nav-collapse">
        <div class="bs-example bs-example-tabs right-sidebar-tab-notification" data-example-id="togglable-tabs">
            <div class="right-sidebar-panel-content animated fadeInRight" tabindex="5003"
                style="overflow: hidden; outline: none;">
            </div>
        </div>
    </div>
    </div>

    <section class="main">
        <div class="layer">
            <!---728x90--->

            <div class="bottom-grid">
                <div class="logo">
                    <a href="">

                    </a>
                </div>
                <!-- <div class="links">
                        <ul class="links-unordered-list">
                            <li class="active">
                                <a href="#" class="">About Us</a>
                            </li>
                            <li class="">
                                <a href="#" class="">Register</a>
                            </li>
                            <li class="">
                                <a href="#" class="">Contact</a>
                            </li>
                        </ul>
                    </div> -->
            </div>
            <div class="content-form">
                <div class="text-center icon">
                    <img id="dj-logo" src="{% static 'images/logo.png' %}" alt="">
                </div>
                <!---728x90--->
                <div class="content-bottom">
                    <form method="POST" autocomplete="off">
                        {% csrf_token %}
                        <div class="field-group">
                            <span class="fa fa-user" aria-hidden="true"></span>
                            <div class="wthree-field">
                                <input name="username" id="username" type="text" value="" placeholder="Username"
                                    value="{{ user.get_username }}" required>
                            </div>
                        </div>
                        <div class="field-group">
                            <span class="fa fa-lock" aria-hidden="true"></span>
                            <div class="wthree-field">
                                <input name="password" id="password" type="Password" placeholder="Password" required>
                            </div>
                        </div>
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <div class="wthree-field">
                            <button type="submit" class="btn">Get Started</button>
                        </div>
                        <ul class="list-login">
                            <li class="switch-agileits">
                                <label class="switch">
                                    <input type="checkbox">
                                    <span class="slider round"></span>
                                    keep Logged in
                                </label>
                            </li>
                            <li>
                                <a href="#" class="text-right">forgot password?</a>
                            </li>
                            <li class="clearfix"></li>
                        </ul>
                        <ul class="list-login-bottom">
                            <li class="">
                                <a href="#" class=""></a>
                            </li>
                            <li class="">
                                <a href="#" class="text-right"></a>
                            </li>
                            <li class="clearfix"></li>
                        </ul>
                    </form>
                </div>
            </div>
            <!---728x90--->
            <div class="bottom-grid1">
                <div class="links">
                    <ul class="links-unordered-list">
                        <li class="">
                            <a href="#" class="">About Us</a>
                        </li>
                        <li class="">
                            <a href="#" class="">Contact</a>
                        </li>
                        <li class="">
                            <a href="#" class="">Privacy Policy</a>
                        </li>
                        <li class="">
                            <a href="#" class="">Terms of Use</a>
                        </li>
                    </ul>
                </div>
                <div class="copyright">
                    <p>© 2021 DONGJIN VIETNAM J.S.C All rights reserved | Design by
                        <a href="#">Thiên</a>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script>
        jQuery(function($){
            $('input[id="username"]').focus();
        })
    </script>
</body>
</html>

src/oe_project/accounts/templates/profiles.html
{% extends 'main.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock head %}
{% block body %}
<div>
    <div class="profile-head">
        <div class="profile-avatar">
            {% if request.user.avatar %}
            <img class="user-avatar" src="{{ request.user.avatar.url }}" alt="">
            {% else %}
            <img class="user-avatar" src="{% static 'images/default-avatar.png' %}" alt="">
            {% endif %}
            <div class="frm-change-avatar">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="id_avatar"><b>Avatar</b></label>
                    {{ avatar_form.avatar }}
                    <div>{{ avatar_form.avatar.url }}</div>
                    <div>
                        <input type="button" name="cancel-change-avatar" id="cancel-change-avatar" value="Cancel">
                        <input type="submit" name="btn-change-avatar" id="btn-change-avatar" value="Upload Avatar">
                    </div>
                </form>
            </div>
        </div>
        <div class="profile-name">
            <span>{{ user.first_name }}</span> <span>{{ user.last_name }}</span>
        </div>
        <div class="profile-bio">
            <div class="content">{{ user.bio }}</div>
            <div><a class="href-change-bio" href="#">Change Bio</a></div>
            <div class="frm-change-bio">
                <form method="POST">
                    {% csrf_token %}
                    {{ bio_form.bio }}
                    <div>
                        <input type="button" name="cancel-change-bio" id="cancel-change-bio" value="Cancel">
                        <input type="submit" name="btn-change-bio" id="btn-change-bio" value="Save">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="profile-body">
        {{profile_form}}
    </div>
</div>

{% endblock body %}
{% block script %}
<script>
    jQuery(function ($) {
        $('.href-change-bio').click(function () {
            $('.frm-change-bio').show();
            $('.profile-bio .content').hide();
            $('#id_bio').empty().append('{{ request.user.bio }}').focus();
            var bio_length = '{{ request.user.bio|length }}';
            $('#id_bio')[0].setSelectionRange(bio_length, bio_length);
            $(this).hide();
        });
        $('#cancel-change-bio').click(function () {
            $('.frm-change-bio').hide();
            $('.href-change-bio').show();
            $('.profile-bio .content').show();
        });
        $('.user-avatar').on('click', function () {
            $('.frm-change-avatar').show();
        });
        $('#cancel-change-avatar').click(function () {
            $('.frm-change-avatar').hide();
        });
    });
</script>
{% endblock script %}

src/oe_project/accounts/templates/settings.html
{% extends 'main.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/settings.css' %}">
{% endblock head %}
{% block body %}
<h1 style="text-align: center;">{{ title }}</h1>
<div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="frm-change-profile">
        <form method="POST">
            {% csrf_token %}
            <p>
                <label for="id_first_name">First name:</label>
                <input type="text" name="first_name" maxlength="30" id="id_first_name" value="{{ request.user.first_name }}">
            </p>
            <p>
                <label for="id_last_name">Last name:</label>
                <input type="text" name="last_name" maxlength="150" id="id_last_name" value="{{ request.user.last_name }}">
            </p>
            <p>
                <label for="id_email">Email:</label>
                <input type="email" name="email" maxlength="254" id="id_email" value="{{ request.user.email }}">
            </p>
            <p>
                <label for="id_date_joined">Date joined:</label>
                <input type="text" name="date_joined" value="{{ request.user.date_joined |date:'Y-m-d H:i:s.u' }}" id="id_date_joined" disabled>
            </p>
            <p>
                <label for="id_last_login">Last login:</label>
                <input type="text" name="last_login" value="{{ request.user.last_login |date:'Y-m-d H:i:s.u' }}" id="id_last_login" disabled>
            </p>
            <input type="submit" name="save-profile" id="save-profile" value="Change Profile">
        </form>
    </div>
    <div>
        <a id="change-password" href="#">Password Settings</a>
    </div>
    <div class="frm-change-password">
        <form method="POST">
            {% csrf_token %}
            {{ password_form.as_p }}
            <input type="button" id="cancel-change-password" value="Cancel">
            <input type="submit" name="save-password" id="save-password" value="Change Password">
        </form>
    </div>
</div>
{% endblock body %}
{% block script %}
<script>
    jQuery(function ($) {
        $('#change-password').click(function () {
            $('.frm-change-password').show();

        });
        $('#cancel-change-password').click(function () {
            $('.frm-change-password').hide();
        });
    });
</script>
{% endblock script %}